name: Close all Pull Requests and comment on them
on: [pull_request]
jobs:
  close-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Close Pull
        uses: peter-evans/close-pull@v1
        with:
          comment: Auto-closing pull request
          delete-branch: true
