name: Close all Pull Requests and comment on them
on: [pull_request]
jobs:
  close-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Close Pull
        uses: peter-evans/close-pull@v1
        with:
          comment: ${{ .Files.Get ".github/close-pr-template.md" }}
          delete-branch: true
